### PR TITLE
chore: new companies -> adopters page

### PR DESCRIPTION
**Pull request by hacktivist123**
This PR adds the following companies to the adopters page:

- Netways 
- Sealos

### CODE REVIEW

**Comment by xmulligan** [comment]
can you also add them to the "Deploy on your preferred cloud" section too?

**Comment by hacktivist123** [comment]
Good catch, missed it! Will add them now

**Comment by xmulligan** [comment]
Screenshot 2024-01-31 at 17 38 13
the netways logo looks larger than the others, can you fix?

**Comment by xmulligan** [comment]
Screenshot 2024-01-31 at 18 34 27
slightly off center now 😅

**Comment by xmulligan** [comment]
Screenshot 2024-02-01 at 08 36 56
same problem

**Comment by hacktivist123** [comment]
@yasell the Netways logo in the deploy on your preferred cloud section is too big, that was the origin of the problem. 

We want it to be smaller and also aligned properly with the rest of the logos

**Comment by yasell** [comment]
Hey @hacktivist123 👋

I made the `Netways` logo similar to the others 🙌.

**Comment by hacktivist123** [comment]
Thanks, looks good. 

@xmulligan i think it's ready for merge!

**Review by xmulligan — APPROVED** [review]

**Pull request merged**
