### PR TITLE
add cilium on DigitaOcean interview

### PR DESCRIPTION
**Pull request by hacktivist123**
This PR adds the Cilium on Digital Ocean exclusive interview to the blog

### CODE REVIEW

**Comment by xmulligan** [comment]
can you make the questions italic?

**Comment by hacktivist123** [comment]
> can you make the questions italic?

sure thing, can definitely do that

**Comment by xmulligan** [comment]
Sorry one more thing, can you add "Interview:" to the title so don't think the Cilium project is announcing a vendor feature?

**Comment by hacktivist123** [comment]
> Sorry one more thing, can you add "Interview:" to the title so don't think the Cilium project is announcing a vendor feature?

sure thing!

**Review by xmulligan — APPROVED** [review]

**Pull request merged**
