### PR TITLE
fix: rephrased setup command

### PR DESCRIPTION
**Pull request by Neilblaze**
### Description:
Added the example command `cp .env.example .env` under [bullet 3](https://github.com/Neilblaze/cilium.io/blob/main/README.md#:~:text=Copy%20.env.example%20and%20rename%20it%20into%20.env) in Getting Started.

Fixes: #244 
cc: @xmulligan, @Oms-343

### CODE REVIEW

**Comment by Oms-343** [comment]
great @Neilblaze  can you just make a small update. the 3rd point should say
3rd." Copy .env.example file  and rename it into a new file  .env   " 
`cp .env.example .env`.
thankyou✌

**Comment by Neilblaze** [comment]
> the 3rd point should say 3rd." Copy .env.example file and rename it into a new file .env 

The command **`cp`** stands for **copy** in general, and since technically it's doing a register-indirect data shift to `.env.example` from `.env`, I think the new command suffices that by itself & hence, we don't need to update anything for now.

**Comment by Oms-343** [comment]
Ok done👍

**Comment by thebsdbox** [comment]
`/lgtm` I think this is perfectly understandable at this point, along with the code snippet.

**Review by thebsdbox — APPROVED** [review]

**Comment by Oms-343** [comment]
Yup👍

**Review by xmulligan — APPROVED** [review]

**Comment by xmulligan** [comment]
Thanks for the help!

**Pull request merged**
