### PR TITLE
chore: update adopters page

### PR DESCRIPTION
**Pull request by hacktivist123**
Updates to the adopters page

### CODE REVIEW

**Comment by xmulligan** [comment]
Screenshot 2024-01-03 at 11 41 00

looks like something is wrong in the preview

**Comment by hacktivist123** [comment]
@xmulligan looks different on mine, I'll check what is wrong and update

**Comment by hacktivist123** [comment]
Should be fixed now! It was due to me not saving the changes I made to the SVG file locally before pushing.

**Comment by xmulligan** [comment]
Screenshot 2024-01-03 at 14 25 01
 
Looks like it makes the boxes really big. Can you shorten it a bit so it is roughly the same size as the others?

**Comment by hacktivist123** [comment]
should be better now @xmulligan

**Review by xmulligan — APPROVED** [review]

**Pull request merged**
