### PR TITLE
chore: add new tetragon logos and hyperlink

### PR DESCRIPTION
**Pull request by hacktivist123**
This PR adds tetragon.io as a hyperlink for the word "tetragon" in the runtime enforcement page and updates the tetragon logos and illustrations where necessary.

### CODE REVIEW

**Comment by xmulligan** [comment]
Doesn't look like the links have been added

Can you also update this image to the new logo?

Screenshot 2023-11-03 at 10 47 28

**Comment by hacktivist123** [comment]
> Doesn't look like the links have been added
> 
> Can you also update this image to the new logo?
> 
> Screenshot 2023-11-03 at 10 47 28

I can update the logo, do you want me to do that in this PR or in a separate one?

**Comment by xmulligan** [comment]
Screenshot 2023-11-03 at 11 54 13
Can you also update this image too on the use case page?

**Comment by xmulligan** [comment]
It also doesn't look very nice either 😅

**Comment by xmulligan** [comment]
I would take the one from the Tetragon homepage

**Comment by hacktivist123** [comment]
oh yeah, i missed this, i actually created the new ones on the tetragon home page

**Review by xmulligan — APPROVED** [review]

**Pull request merged**
