### PR TITLE
style: update pages design

### PR DESCRIPTION
**Pull request by nikvoblikov**
**This PR:**
- Updates the ItemCard style in Highlights components;

**Preview**
- Preview [Home page](https://deploy-preview-324--cilium.netlify.app/)
- Preview [Case page](https://deploy-preview-324--cilium.netlify.app/use-cases/cni/)

**Steps to test**
- [x] Open the preview pages;
- [x] Confirm that everything looks and works as expected;

### CODE REVIEW

**Comment by xmulligan** [comment]
This is great, can you also add a "Use Cases" drop down at the top with "Security, Networking, Observability" being the choices with links to the relevant sections on the homepage?

**Comment by nikvoblikov** [comment]
> This is great, can you also add a "Use Cases" drop down at the top with "Security, Networking, Observability" being the choices with links to the relevant sections on the homepage?

done

**Comment by xmulligan** [comment]
Thanks! Last things, can you add an arrow or something else to the cards on the homepage so that people know they should click them? I think we had this before but it got removed in the redesign

**Comment by xmulligan** [comment]
Thanks!

**Review by xmulligan — APPROVED** [review]

**Pull request merged**
